//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TICKETNO { get; set; }
        public int EMPNO { get; set; }
        public string PROJECTNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATECREATION { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
