CREATE TABLE [dbo].[Employee]
(
	[EMPNO] INT NOT NULL PRIMARY KEY,
	[ENAME] VARCHAR(100) NOT NULL ,
	[DEPNO] INT NOT NULL,
	CONSTRAINT [FK_Dept_Emp] FOREIGN KEY([DEPNO]) REFERENCES [dbo].[Department] ([DEPNO])
)