CREATE TABLE [dbo].[Ticket]
(
	[TICKETNO] INT NOT NULL PRIMARY KEY,
	[EMPNO] int NOT NULL,
	[PROJECTNAME] NVARCHAR(MAX) NOT NULL ,
	[DESCRIPTION] varchar(255) NOT NULL,
	[DATECREATION] datetime NOT NULL,
	CONSTRAINT [FK_Ticket_Emp] FOREIGN KEY([EMPNO]) REFERENCES [dbo].[Employee] ([EMPNO])
)